development:
  adapter: postgresql
  database: direct_upload_development
  username: pierre
  host: localhost
  encoding: UTF8
test:
  adapter: postgresql
  database: direct_upload_test
  username: pierre
  host: localhost
  encoding: UTF8
  min_messages: WARNING
